### ISSUE TITLE
Create initial routing

### ISSUE THREAD

**Issue by Lukortech** [Lukortech-org/React-Typescript#3]
For our application we'd like to have 3 basic routes.

We'll need layout that'll have 2 versions of it inside based on the URL we're in. 
We're going to create a folder structure corresponding to the page structure.

- src
  - pages
    - home
    - auth
  - components
    - layout
    - navbar
    - footer

We don't need any input more than the page name rendered. 
For components we can have a copy-paste of MUI examples available here: https://mui.com/material-ui/react-app-bar/

Layout is the HOC that'll wrap anything happening inside the routes. https://reactrouter.com/en/main/components/outlet

**Comment by Qubaka** [comment]
Done #11
